### ISSUE TITLE
Get接口，浏览器能直接访问调用，但工具不行，疑似URL编码问题

### ISSUE THREAD

**Issue by guicaiyue** [coder-hxl/x-crawl#113]
### Bug 预期

预期：浏览器可直接调用成功
实际：接口调用失败，因为无法识别url

### 最小可重复的例子

```TypeScript
import { createCrawl } from 'x-crawl'

const crawlApp = createCrawl({ intervalTime: { max: 3000, min: 1000 } })
let aar =["https://suno-list.com/api/suno/validateLink?link=https%3A%2F%2Fsuno.com%2Fsong%2Fe8b369f2-e2fc-4152-b2aa-d29224d43041"]
    crawlApp.crawlData({ aar }).then((twoRes) => {
        // 处理接口链接
        console.log(twoRes);
        for(let one of twoRes){
            // 这里报错
        }
        console.log(downloadLinks);
    });
```

### 报错信息

TypeError: Invalid URL

### x-crawl 版本

x-crawl 10.0.1

### Node 版本

v20.12.1

### 包管理器

pnpm

### 包管理器版本

8.3.1

**Comment by guicaiyue** [comment]
> 你好，你这个用法是错误的，这样会导致 x-crawl 无法正确获取 URL ，看示例应该用的是 [混合目标数组配置](https://coder-hxl.github.io/x-crawl/cn/api/crawl-data#mixed-target-array-configuration---(string-%7C-CrawlDataDetailTargetConfig)%5B%5D) 或者 [进阶配置](https://coder-hxl.github.io/x-crawl/cn/api/crawl-data#advanced-configuration---crawldataadvancedconfig)
> 
> 正确的配置
> 
> ```js
> crawlApp.crawlData(aar)
> // 或者
> crawlApp.crawlData({ targets: aar })
> ```
> 
> 错误的配置
> 
> ```js
> crawlApp.crawlData({ aar })
> ```
> 
> x-crawl 没有 aar 选项

懂了，我知道问题的原因了

**Comment by guicaiyue** [comment]
> 建议搭配 TypeScript 使用

请问我如何实现zip文件的解压，因为工具是ECMAScript 模块，试了adm-zip，没法使用，因为它是CommonJS 模块

**Comment by coder-hxl** [comment]
@guicaiyue ESM 可以导入 CJS，现在 Node.js 22 版本的 CJS 也能导入 ESM 了

**Comment by guicaiyue** [comment]
> @guicaiyue ESM 可以导入 CJS，现在 Node.js 22 版本的 CJS 也能导入 ESM 了

还是没做到，我现在是在青龙面板里面常用使用这个脚本，每个脚本都是单个ts文件，所以无法同时支持ECMAScript 与CommonJS 模块吧，但 fs 也是能用，nodejs的CJS 和 ESM 割裂性也太强烈了
```
import { createCrawl } from 'x-crawl';
import fs from 'fs';
import AdmZip from 'adm-zip';
```

**Comment by coder-hxl** [comment]
@guicaiyue 有什么报错信息不

**Comment by guicaiyue** [comment]
找不到模块的异常，人麻了
![image](https://github.com/coder-hxl/x-crawl/assets/43875377/3358f550-7a96-42fd-b84f-a2986de7bde7)

**Comment by coder-hxl** [comment]
@guicaiyue 把 node_modules 删了重新下载试试
