### ISSUE TITLE
无法在nest.js使用，The CJS version of x-crawl has been deprecated.

### ISSUE THREAD

**Issue by xiaobailong007** [coder-hxl/x-crawl#118]
### Bug 预期

支持cjs格式

### 最小可重复的例子

```TypeScript
无
```

### 报错信息

The CJS version of x-crawl has been deprecated.

### x-crawl 版本

v10.0.1

### Node 版本

v20.13.0

### 包管理器

npm

### 包管理器版本

pnpm

**Comment by coder-hxl** [comment]
你好，请参考 #89
