### ISSUE TITLE
请问有跳转的文件下载如何处理

### ISSUE THREAD

**Issue by KaneOne** [coder-hxl/x-crawl#14]
感谢提供这么好用的工具，正在学习中，在使用过程中，有些网站并不提供固定的文件下载地址，而是一个页面后，再跳转（302或返回一段js）直到实际的下载地址，这个地址也是临时的（所以没法事先抓取），请问这种情况如何处理，感谢~

**Comment by coder-hxl** [comment]
你调用 crawlPage API 后，可以拿到 jsdom 和 page 两个实例对象，通过 jsdom.window.document.querySelector() 找到某个元素，获取要跳转页面的 URL ，然后调用 [page.goto()](https://pptr.dev/api/puppeteer.page.goto) 跳转到那个页面，最后获取下载链接进行下载。

**Comment by coder-hxl** [comment]
如果感觉不错，可以给 [x-crawl 存储库](https://github.com/coder-hxl/x-crawl) 点个 Star 支持一下，您的 Star 将是我更新的动力。

**Comment by coder-hxl** [comment]
如果感觉不错，可以给 [x-crawl 存储库](https://github.com/coder-hxl/x-crawl) 点个 Star 支持一下，您的 Star 将是我更新的动力。
