### ISSUE TITLE
crawlApp.crawlData爬取接口数据的时候，如何给接口传递请求头参数呢？

### ISSUE THREAD

**Issue by yeyuliang2015** [coder-hxl/x-crawl#143]
### Bug expectation

crawlApp.crawlData爬取接口数据的时候，如何给接口传递请求头参数呢？

### Minimal, reproducible example

```TypeScript
crawlApp.crawlData爬取接口数据的时候，如何给接口传递请求头参数呢？
```

### Error string

crawlApp.crawlData爬取接口数据的时候，如何给接口传递请求头参数呢？

### x-crawl version

10.0.2

### Node version

v20.13.1

### Package manager

npm

### Package manager version

10.5.2

**Comment by yeyuliang2015** [comment]
crawlApp.crawlData爬取接口数据的时候，如何给接口传递请求头参数呢？

**Comment by coder-hxl** [comment]
请查看 
https://coder-hxl.github.io/x-crawl/cn/type/crawl-data#crawldatadetailtargetconfig
https://coder-hxl.github.io/x-crawl/cn/type/crawl-data#crawldataadvancedconfig
https://coder-hxl.github.io/x-crawl/cn/type/crawl-data#crawldatasingleresult

根据你选择写法配置就行了
