### ISSUE TITLE
pnpm 安装依赖报错

### ISSUE THREAD

**Issue by Jeffrey-mu** [coder-hxl/x-crawl#22]
### Bug 预期

mac系统
报错信息
```
node_modules/.pnpm/puppeteer@19.8.0/node_modules/puppeteer: Running postinstall script, failed in 5.2s
.../node_modules/puppeteer postinstall$ node install.js
│ ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
│ Error: read ECONNRESET
│     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
│   errno: -54,
│   code: 'ECONNRESET',
│   syscall: 'read'
│ }
└─ Failed in 5.2s
```

### 最小可重复的例子

```TypeScript
pnpm i xxx
```

### 报错信息

node_modules/.pnpm/puppeteer@19.8.0/node_modules/puppeteer: Running postinstall script, failed in 5.2s .../node_modules/puppeteer postinstall$ node install.js │ ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download. │ Error: read ECONNRESET │     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) { │   errno: -54, │   code: 'ECONNRESET', │   syscall: 'read' │ } └─ Failed in 5.2s

### x-crawl 版本

最新

### Node 版本

v18.6.0

### 包管理器

pnpm

### 包管理器版本

7.14.2

**Comment by coder-hxl** [comment]
你好，可以试试 `pnpm i puppeteer` 看看是否会出现同样的报错

**Comment by Jeffrey-mu** [comment]
已解决

**Comment by coder-hxl** [comment]
v6 大版本即将发布，变化挺大的，到时候可以试试哦
