### ISSUE TITLE
crawlPage setting proxy option does not work

### ISSUE THREAD

**Issue by floatcat** [coder-hxl/x-crawl#36]
### Bug expectation

crawlPage 设置 proxy 选项无效
环境: window10 操作系统， node 16，npm v8.19
我使用 clash 作为代理，在不开系统代理的情况下，crawlData工作良好，但 crawlPage 的 proxy 配置无效，只走系统代理

代码如下
```TypeScript
import xCrawl from 'x-crawl'

// Application instance configuration
const testXCrawl = xCrawl({
  proxy: {
    urls: [
      'https://127.0.0.1:7890'
    ],
    switchByErrorCount: 1,
    switchByHttpStatus: [401, 403]
  }
})

// Advanced configuration
testXCrawl
  .crawlPage({
    targets: [
      'https://www.google.com',
      {
        url: 'https://www.google.com',
        proxy: { urls: ['http://127.0.0.1:7890'] }
      }
    ],
    maxRetry: 3,
    proxy: {
      urls: [
        'http://127.0.0.1:7890',
        'http://127.0.0.1:7890'
      ],
      switchByErrorCount: 1,
      switchByHttpStatus: [401, 403]
    }
  })
  .then((res) => {})
```

考虑到 switchByHttpStatus 可能会影响
我修改了 x-crawl index.mjs 第 270 行，加了下列代码
`  if (status === null) {
    result = true;
  }`

### Error string

no error

### x-crawl version

7.0.1

### Node version

16.18

### Package manager

npm

### Package manager version

8.19

**Comment by coder-hxl** [comment]
你那有获取失败不？我用的也是 Clash 代理。

**Comment by floatcat** [comment]
是的获取失败了，直至到 maxRetry，在 clash log 都看不到走代理的记录
clash 需要关闭 系统代理才能复现

**Comment by coder-hxl** [comment]
有可能是网速原因

**Comment by floatcat** [comment]
是的，是网络问题，我有些站点在国外，需要启用代理
如果 crawlPage 走代理，他会在 clash 留下记录，但没有相应记录
（刚刚误操作，按到了 关闭 issue）

**Comment by coder-hxl** [comment]
也有可能是 Clash 的问题。案例在我这里是正常的，同时也在 Clash logs 中有相应的记录。

**Comment by coder-hxl** [comment]
你可以检查一下 Clash 的配置是否有问题。
