### ISSUE TITLE
关于 `crawlFile` API 设计的想法建议

### ISSUE THREAD

**Issue by winner106** [coder-hxl/x-crawl#42]
### 这个特性解决了什么问题？

作者好，感谢提供这样的一个库，非常好用！但我觉得代码中的类型声明部分存在一些冗余和不够灵活的地方，可能会给用户在使用函数时带来一些限制和不便。以`crawlFile`为例：

1、`url` 明显是必需的参数，建议将其作为单独的参数更直观和灵活。
2、将 CrawlFileDetailTargetConfig 和 CrawlFileAdvancedConfig 合并为一个更简洁的 CrawlFileConfig 类型，减少重复定义。
3、支持传入单个 URL 或多个 URL，以及为每个 URL 设置单独的存储目录、文件名和扩展名。

我尝试给出`ts`的类型作为参考，以便清楚地表达我的建议，希望这个库可以越来越火。

还有个小建议， 可以把`crawFile`改名成`fetchFile`，  因为 "fetch" 一词表示从网络获取数据的常见操作，结合 "file" 可以清晰地表达其作用。

### 提议的 API 是什么样的？

```ts
export function crawlFile(
  url: string | string[],
  config?: CrawlFileConfig,
  callback?: (result: CrawlFileSingleResult | CrawlFileSingleResult[]) => void
): Promise<CrawlFileSingleResult | CrawlFileSingleResult[]>

export interface CrawlFileConfig extends CrawlCommonConfig {
  outputDir?: string | string[] | null
  extension?: string | string[] | null
  fileName?: string | string[] | null
  intervalTime?: IntervalTime
  fingerprints?: DetailTargetFingerprintCommon[]
  headers?: AnyObject
  onCrawlItemComplete?: (result: CrawlFileSingleResult) => void
  onBeforeSaveItemFile?: (info: {
    id: number
    fileName: string
    filePath: string
    data: Buffer
  }) => Promise<Buffer>
}
```

**Comment by coder-hxl** [comment]
关于 API 的多种参数写法设计，是出于正确的参数、数量返回值、类型限制等方面考虑的。

写法对比：

- 统一写法：
  - 正确的参数：容易产生混乱，比如在爬取一个目标时，那么像 outputDir、extension、fileName 等数组写法 和 intervalTime 这种将不应该传进来。
  - 数量返回值：难以确定详情对象是否存放在一个数组中，有些结果不一定会想存放于数组中，否则拿的时候还得取出来。

- 多种写法：
  - 正确的参数：不会产生混乱，因为每种写法的参数都是确定好的。
  - 数量返回值：会自动根据你选用的配置方式决定详情对象是否存放在一个数组中。

经过对比还是采用原先写法更好，感谢您为 x-crawl 的建议。

**Comment by winner106** [comment]
好的， 明白了， 谢谢~

**Comment by coder-hxl** [comment]
在使用上也是会增加成本并且类型限制相当于没了，还得让使用者考虑 outputDir 是传数组还是字符串，如果他传入个数组岂不是故意乱传。

**Comment by winner106** [comment]
故意乱传的话无论如何都无法避免，只需要抛出错误即可。我个人的习惯是觉得调整后的传法很自然，也方便添加jsdoc在ide中有提示文档，使用者无需跳出文档，理解起来也很直观，没有记忆负担
