### ISSUE TITLE
crawlPage 爬取多个 link 时, 返回结果是数组, 但是不知道每个结果对应的原始 url

### ISSUE THREAD

**Issue by myfjdthink** [coder-hxl/x-crawl#55]
### 这个特性解决了什么问题？

避免重复爬取某个 page,  看下面这个例子

```js
const ress = await myXCrawl.crawlPage({
    targets: ['https://docs.aave.com/portal/'],
    viewport: { width: 1920, height: 1080 },
    intervalTime: { max: 2000, min: 1000 },
    maxRetry: 3,
});

for (const res of ress) {
    const { browser, page } = res.data;
    console.log(page.url());
    await page.waitForNetworkIdle();
    const content = await page.content();
    console.log(page.url());
}
```

https://docs.aave.com/portal/ 会跳转到 https://docs.aave.com/hub/ 
通过 page.url() 获取的是调整后的 link,  这样我就无法根据 link 来判断一个page是否已经被爬取过了

### 提议的 API 是什么样的？

返回结果提供原始的 link

**Comment by coder-hxl** [comment]
使用 `targets[res.id - 1]` 可以拿到对应的 URL ， 使用 `res.id` 搭配 `res.isSuccess` 可以知道哪些爬取是否成功。

`id` 和 `isSuccess` 可以参考 [关于结果](https://github.com/coder-hxl/x-crawl/blob/main/docs/cn.md#%E5%85%B3%E4%BA%8E%E7%BB%93%E6%9E%9C)
