### ISSUE TITLE
能否增加debug模式，在开发的时候，支持将浏览器显示出来？

### ISSUE THREAD

**Issue by yuexuan** [coder-hxl/x-crawl#6]
如题。开发调试的时候，方便把浏览器打开。不然只能盲猜测

**Comment by coder-hxl** [comment]
已经把浏览器实例暴露出来了，你可以参考 crawlPage 返回的 [broswer](https://github.com/coder-hxl/x-crawl/blob/main/docs/cn.md#browser)

**Comment by coder-hxl** [comment]
浏览器实例他是个无头浏览器，并无 UI 外壳，他做的是将浏览器渲染引擎提供的**所有现代网络平台功能**带到代码中。

**Comment by yuexuan** [comment]
这些我都清楚的，只是在开发和调试的过程中，比如我需要控制浏览器一直往下滚动，但是很多时候我没办法知道，浏览器是不是在往下一直滚动。如果看不到的话，只能不断的加日志去尝试。我的意思是，你可以在配置里支持一个显示的浏览器的功能，更方便开发去适应不同的场景。当然，你的产品写的也很棒。很简洁。

**Comment by coder-hxl** [comment]
@yuexuan  你可以参考 [page.hover](https://pptr.dev/api/puppeteer.page.hover) 和 [page.screenshot](https://pptr.dev/api/puppeteer.page.screenshot) ，这样可以知道页面发生了什么。

```js
import xCrawl from 'x-crawl'

const testXCrawl = xCrawl({ timeout: 10000 })

testXCrawl
  .crawlPage('https://github.com/coder-hxl/x-crawl/issues/6')
  .then(async (res) => {
    const { page } = res

    await page.hover('.footer')

    await page.screenshot({ path: './upload/img.png' })

    console.log('截屏完毕~')
  })
```

**Comment by yuexuan** [comment]
谢谢，这是一个不错的思路。

**Comment by coder-hxl** [comment]
新版 x-crawl 已经提供启动浏览器的选项，可以打开浏览器进行调试了
