### ISSUE TITLE
是否可以有个选项启用或者关闭打印的 Start Crawling/finish 信息

### ISSUE THREAD

**Issue by cdwmhcc** [coder-hxl/x-crawl#65]
### 这个特性解决了什么问题？

目前看完文档没有发现有控制 log 的配置，在使用其它方法配合 x-crawl 使用的时候会造成控制台输出混乱。

如果可以手动配置，再提供一个 context 就更好了，类似 https://listr2.kilic.dev/task/output.html

### 提议的 API 是什么样的？

这个我不是很专业。

**Comment by coder-hxl** [comment]
已经搞定并发布了，请查看 [v8.3.0](https://github.com/coder-hxl/x-crawl/releases/tag/v8.3.0) 和 [打印信息](https://github.com/coder-hxl/x-crawl/blob/main/docs/cn.md#%E6%89%93%E5%8D%B0%E4%BF%A1%E6%81%AF) 

感谢您的支持和建议

**Comment by cdwmhcc** [comment]
哇，已经在使用了，太好用了。感谢开发者！ @coder-hxl

**Comment by cdwmhcc** [comment]
@coder-hxl 对了, log 的 ts 未更新哦。

``` ts
// XCrawlConfig
export interface XCrawlConfig extends CrawlCommonConfig {
  mode?: 'async' | 'sync'
  enableRandomFingerprint?: boolean
  baseUrl?: string
  intervalTime?: IntervalTime
  crawlPage?: {
    puppeteerLaunch?: PuppeteerLaunchOptions
  }
}
```

**Comment by coder-hxl** [comment]
8.2.0 版本的 ts 也更新了，有可能你用的还是 8.2.0 版本，可以尝试把 node_modules 删了重新下载依赖。

**Comment by coder-hxl** [comment]
8.3 版本的终端输出是这样的，也可以通过运行看看是否用 8.3 版本

![Uploading run-example.gif](https://raw.githubusercontent.com/coder-hxl/x-crawl/main/assets/run-example.gif)

**Comment by cdwmhcc** [comment]
> 8.3 版本的终端输出是这样的，也可以通过运行看看是否用 8.3 版本
> 
> ![Uploading run-example.gif](https://raw.githubusercontent.com/coder-hxl/x-crawl/main/assets/run-example.gif) [ ![Uploading run-example.gif](https://raw.githubusercontent.com/coder-hxl/x-crawl/main/assets/run-example.gif) ](https://raw.githubusercontent.com/coder-hxl/x-crawl/main/assets/run-example.gif) [ ](https://raw.githubusercontent.com/coder-hxl/x-crawl/main/assets/run-example.gif)

是 webstorm 缓存导致的，可以了，太好用了。

**Comment by coder-hxl** [comment]
😄
