### ISSUE TITLE
创建实例时候 报错 TypeError: (0 , x_crawl_1.default) is not a function

### ISSUE THREAD

**Issue by 618457** [coder-hxl/x-crawl#89]
### Bug 预期

执行爬虫实例化时
const myXCrawl = xCrawl();

报错

TypeError: (0 , x_crawl_1.default) is not a function

### 最小可重复的例子

```TypeScript
import xCrawl from 'x-crawl';

  async crawl(path: string) {
    // 2.创建一个爬虫实例
    const myXCrawl = xCrawl();
    myXCrawl.crawlPage(path).then(res => {
      const { browser, page } = res.data;
      console.log(page);
      // 关闭浏览器
      browser.close();
    });
  }
```

### 报错信息

ERROR 389 TypeError: (0 , x_crawl_1.default) is not a function

### x-crawl 版本

8.3.1

### Node 版本

16.19.1

### 包管理器

npm

### 包管理器版本

9.6.1

**Comment by coder-hxl** [comment]
你好，请打印一下 xCrawl 看看是否存在

**Comment by coder-hxl** [comment]
@wencaizhang 我先克隆下来试试

**Comment by wencaizhang** [comment]
> @wencaizhang V10 版本已经不再支持 CJS ，只能使用 ESM ，https://github.com/coder-hxl/x-crawl/releases/tag/v10.0.0 ![image](https://private-user-images.githubusercontent.com/85156687/323985270-4c738df1-0773-440f-8222-dab5d979c0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzU1MzIsIm5iZiI6MTcxMzUzNTIzMiwicGF0aCI6Ii84NTE1NjY4Ny8zMjM5ODUyNzAtNGM3MzhkZjEtMDc3My00NDBmLTgyMjItZGFiNWQ5NzljMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE0MDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NTZiZGVmM2Q0OGY3NTE5MzVjYjNlYTc2NTE4YmY2MmZlNjdhMDcxNWZiMzVjNzkzZGM2NTFjZjY5NTg3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O7Ky9ZmJA_esyR12iPqDsANpt_wp4HY8xDBMHewxfV4)

这个项目是支持 ESM 的，例如 `import { log } from '../utils';` 按照 ESM 写法都是正常的。

但是具体到 x-crawl 我怎么写都不对。

**Comment by coder-hxl** [comment]
@wencaizhang 最终打包是变成 CJS 的，可以看看 dist 目录下的文件
![image](https://github.com/coder-hxl/x-crawl/assets/85156687/e9bfea04-283b-4aad-b935-773e16d3083e)

**Comment by wencaizhang** [comment]
明白了，我的理解是现在 nestjs 中虽然是 ESM 写法：

```js
import { createCrawl } from 'x-crawl';
```

但是实际仍然请求了 `x-crawl` 的 CJS 模块：
<img width="761" alt="image" src="https://github.com/coder-hxl/x-crawl/assets/34718241/7314eb96-918a-450a-a2ae-be46823fb1e3">
而这个模块只输出一个警告信息。

所以真正的问题应该是如何让 nestjs 引入 `x-crawl` 的 ESM 模块了。

**Comment by coder-hxl** [comment]
@wencaizhang  对的，可以给 package.json 添加 `"type": "module"`，tsconfig.json 添加 `"module": "ESNext"`, `"moduleResolution": "Bundler"`,

**Comment by Xyn19961118** [comment]
> @wencaizhang 对的，可以给package.json添加，`"type": "module"`tsconfig.json添加`"module": "ESNext"`,,`"moduleResolution": "Bundler"`

按照这个设置也不行

**Comment by coder-hxl** [comment]
@Xyn19961118 如果用的是 nestjs ，就得让 nestjs 打包变成 ESM ，可以去看看 nestjs 有没有对应的配置

**Comment by KinoshitaHanson** [comment]
看来使用nestjs就用不了这个库了，可惜了

**Comment by wencaizhang** [comment]
实际上这个问题最终已经解决了，不过忘记把解决方案贴出来了。

<img width="689" alt="image" src="https://github.com/user-attachments/assets/f40bd913-d152-403d-a178-422f1cc216e4" />

代码位置：[https://github.com/wencaizhang/nestjs-crawl-bug-demo/blob/main/src/crawler/crawler.service.ts#L15-L18](https://github.com/wencaizhang/nestjs-crawl-bug-demo/blob/main/src/crawler/crawler.service.ts#L15-L18)

**Comment by KinoshitaHanson** [comment]
> > 看来使用nestjs就用不了这个库了，可惜了
> 
> 可以在 nestjs 中使用。
> 
> 实际上这个问题最终已经解决了，不过忘记把解决方案贴出来了。
> 
> <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/34718241/398886278-f40bd913-d152-403d-a178-422f1cc216e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODcxNTEsIm5iZiI6MTczNTI4Njg1MSwicGF0aCI6Ii8zNDcxODI0MS8zOTg4ODYyNzgtZjQwYmQ5MTMtZDE1Mi00MDNkLWExNzgtNDIyZjFjYzIxNmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4MDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTZmNjBmNmMyZjEwZTgzZDVhYzJjZjFmNzNiNzY0YWViYzA1OTMyOGM1NjhjYzlkZjg3YzQ3MDRlMmQzZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.etx6SewNkamLU2X6tPMm9WeXDVAd4GQAGHpxrYQ3j_U">
> 代码位置：https://github.com/wencaizhang/nestjs-crawl-bug-demo/blob/main/src/crawler/crawler.service.ts#L15-L18


试了一下成功了，感谢。 我尝试过使用动态import，但是忘记直接写import()，也会被编译成cjs。

**Comment by koala0x** [comment]
> 打包变成 ESM ，可以去看看 nestjs 有

你能贴下你解决的代码么, 谢谢~

**Comment by coder-hxl** [comment]
> > 看来使用nestjs就用不了这个库了，可惜了
> 
> 可以在 nestjs 中使用。
> 
> 实际上这个问题最终已经解决了，不过忘记把解决方案贴出来了。
> 
> <img alt="图像" width="689" src="https://private-user-images.githubusercontent.com/34718241/398886278-f40bd913-d152-403d-a178-422f1cc216e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NzE1MjgsIm5iZiI6MTczNjQ3MTIyOCwicGF0aCI6Ii8zNDcxODI0MS8zOTg4ODYyNzgtZjQwYmQ5MTMtZDE1Mi00MDNkLWExNzgtNDIyZjFjYzIxNmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDAxMDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzk3MDZiYmNiZmQ1NDdiZjg1NmVhMTMwN2YwOTZmZDdiZmQ1MTRmODQ1NzZhYmVlMmQ3M2ZhOTk0NzVhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WsW2SS-ItJbLv-tnYAAioyivfvPCOV8tv-AttOcu3zg">
> 代码位置：https://github.com/wencaizhang/nestjs-crawl-bug-demo/blob/main/src/crawler/crawler.service.ts#L15-L18


@koala0x 试试这个
